"""
File Generator Tool — AI Twin
Supports: PDF, DOCX, XLSX, PPTX, Markdown, JSON, YAML, TXT, CSV, Code files
"""

import csv
import io
import json
import logging
import os
import re
import uuid
from datetime import datetime

logger = logging.getLogger(__name__)

UPLOADS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "uploads")
os.makedirs(UPLOADS_DIR, exist_ok=True)


def _safe_filename(name: str, ext: str) -> str:
    """Sanitize and build a unique filename."""
    safe = re.sub(r"[^\w\-]", "_", name.strip().lower())[:40]
    ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    uid = uuid.uuid4().hex[:6]
    return f"{safe}_{ts}_{uid}.{ext}"


def _save(data: bytes, filename: str) -> str:
    """Save bytes to uploads dir. Returns relative path."""
    path = os.path.join(UPLOADS_DIR, filename)
    with open(path, "wb") as f:
        f.write(data)
    return os.path.join("uploads", filename)


# ─── Generators ────────────────────────────────────────────────────────────────

def generate_pdf(title: str, content: str, metadata: dict = None) -> str:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2.5 * cm, bottomMargin=2 * cm
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        fontSize=22, spaceAfter=6, textColor=colors.HexColor("#1a1926"), fontName="Helvetica-Bold"
    )
    body_style = ParagraphStyle(
        "CustomBody", parent=styles["Normal"],
        fontSize=11, leading=16, spaceAfter=8, textColor=colors.HexColor("#374151")
    )
    h2_style = ParagraphStyle(
        "H2", parent=styles["Heading2"],
        fontSize=14, spaceAfter=4, textColor=colors.HexColor("#6366f1"), fontName="Helvetica-Bold"
    )

    story = []
    story.append(Paragraph(title, title_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e5e7eb")))
    story.append(Spacer(1, 0.3 * cm))

    # Metadata table
    if metadata:
        meta_data = [[k, str(v)] for k, v in metadata.items()]
        meta_table = Table(meta_data, colWidths=[4 * cm, 12 * cm])
        meta_table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#6366f1")),
            ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#6b7280")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.4 * cm))

    # Parse sections from content (## headings)
    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 0.15 * cm))
        elif stripped.startswith("## "):
            story.append(Paragraph(stripped[3:], h2_style))
        elif stripped.startswith("# "):
            pass  # already used as title
        elif stripped.startswith("- ") or stripped.startswith("* "):
            story.append(Paragraph(f"• {stripped[2:]}", body_style))
        else:
            story.append(Paragraph(stripped.replace("<", "&lt;").replace(">", "&gt;"), body_style))

    # Footer
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e5e7eb")))
    footer_style = ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#9ca3af"))
    story.append(Paragraph(f"Generated by AI Twin Intelligence • {datetime.utcnow().strftime('%B %d, %Y')}", footer_style))

    doc.build(story)
    buf.seek(0)
    filename = _safe_filename(title, "pdf")
    return _save(buf.read(), filename), filename


def generate_docx(title: str, content: str, metadata: dict = None) -> str:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()
    # Title
    heading = doc.add_heading(title, 0)
    heading.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = heading.runs[0]
    run.font.color.rgb = RGBColor(0x1a, 0x19, 0x26)
    run.font.size = Pt(22)

    if metadata:
        tbl = doc.add_table(rows=0, cols=2)
        tbl.style = "Table Grid"
        for k, v in metadata.items():
            row = tbl.add_row().cells
            row[0].text = k
            row[1].text = str(v)
        doc.add_paragraph("")

    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph("")
        elif stripped.startswith("## "):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith("# "):
            pass
        elif stripped.startswith("- ") or stripped.startswith("* "):
            p = doc.add_paragraph(stripped[2:], style="List Bullet")
        else:
            doc.add_paragraph(stripped)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    filename = _safe_filename(title, "docx")
    return _save(buf.read(), filename), filename


def generate_xlsx(title: str, data_rows: list, headers: list = None, metadata: dict = None) -> str:
    """data_rows: list of lists or list of dicts"""
    import openpyxl
    from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
    from openpyxl.utils import get_column_letter

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = title[:30]

    header_fill = PatternFill(start_color="6366F1", end_color="6366F1", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    alt_fill = PatternFill(start_color="F5F3FF", end_color="F5F3FF", fill_type="solid")
    thin = Side(style="thin", color="E5E7EB")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    row_offset = 1
    if metadata:
        ws.cell(row=1, column=1, value=title).font = Font(bold=True, size=14, color="1A1926")
        row_offset = 2
        for k, v in metadata.items():
            ws.cell(row=row_offset, column=1, value=k).font = Font(bold=True, color="6366F1")
            ws.cell(row=row_offset, column=2, value=str(v))
            row_offset += 1
        row_offset += 1

    # Convert dicts to rows
    if data_rows and isinstance(data_rows[0], dict):
        if not headers:
            headers = list(data_rows[0].keys())
        data_rows = [[row.get(h, "") for h in headers] for row in data_rows]

    # Headers
    if headers:
        for col_idx, h in enumerate(headers, 1):
            cell = ws.cell(row=row_offset, column=col_idx, value=h)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center")
            cell.border = border
        row_offset += 1

    # Data
    for r_idx, row in enumerate(data_rows):
        for col_idx, val in enumerate(row, 1):
            cell = ws.cell(row=row_offset + r_idx, column=col_idx, value=val)
            cell.border = border
            if r_idx % 2 == 1:
                cell.fill = alt_fill

    # Auto-size columns
    for col in ws.columns:
        max_len = max((len(str(c.value)) if c.value else 0) for c in col)
        ws.column_dimensions[get_column_letter(col[0].column)].width = min(max_len + 4, 40)

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    filename = _safe_filename(title, "xlsx")
    return _save(buf.read(), filename), filename


def generate_pptx(title: str, slides: list) -> str:
    """slides: list of {"title": str, "content": str or list}"""
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor

    prs = Presentation()
    # Title slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    if slide.placeholders[1]:
        slide.placeholders[1].text = f"Generated by AI Twin • {datetime.utcnow().strftime('%B %Y')}"

    # Content slides
    content_layout = prs.slide_layouts[1]
    for s in slides:
        sl = prs.slides.add_slide(content_layout)
        sl.shapes.title.text = s.get("title", "")
        body = sl.placeholders[1].text_frame
        body.clear()
        content = s.get("content", "")
        if isinstance(content, list):
            for item in content:
                p = body.add_paragraph()
                p.text = str(item)
                p.level = 0
        else:
            for line in str(content).split("\n"):
                if line.strip():
                    p = body.add_paragraph()
                    p.text = line.strip().lstrip("- *•")
                    p.level = 1 if line.startswith("  ") else 0

    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    filename = _safe_filename(title, "pptx")
    return _save(buf.read(), filename), filename


def generate_text_file(title: str, content: str, ext: str = "txt") -> str:
    filename = _safe_filename(title, ext)
    return _save(content.encode("utf-8"), filename), filename


def generate_csv(title: str, data_rows: list, headers: list = None) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    if headers:
        writer.writerow(headers)
    elif data_rows and isinstance(data_rows[0], dict):
        headers = list(data_rows[0].keys())
        writer.writerow(headers)
        data_rows = [[row.get(h, "") for h in headers] for row in data_rows]
    writer.writerows(data_rows)
    filename = _safe_filename(title, "csv")
    return _save(buf.getvalue().encode("utf-8"), filename), filename


def generate_json_file(title: str, data: dict | list) -> str:
    content = json.dumps(data, indent=2, ensure_ascii=False)
    filename = _safe_filename(title, "json")
    return _save(content.encode("utf-8"), filename), filename


# ─── Master Dispatcher ─────────────────────────────────────────────────────────

MIME_MAP = {
    "pdf": "application/pdf",
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "txt": "text/plain",
    "md": "text/markdown",
    "csv": "text/csv",
    "json": "application/json",
    "yaml": "text/yaml",
    "yml": "text/yaml",
    "py": "text/x-python",
    "js": "text/javascript",
    "ts": "text/typescript",
    "html": "text/html",
    "css": "text/css",
    "sql": "text/x-sql",
    "sh": "text/x-shellscript",
}


def detect_file_type(user_input: str, ai_decision: str = None) -> str:
    """Detect best file type from user message or AI decision."""
    text = (ai_decision or user_input).lower()
    if any(w in text for w in ["pdf", "report", "invoice", "resume", "cv"]): return "pdf"
    if any(w in text for w in ["word", "docx", "document", "letter", "proposal"]): return "docx"
    if any(w in text for w in ["excel", "xlsx", "spreadsheet", "sheet", "expenses", "budget", "table"]): return "xlsx"
    if any(w in text for w in ["pptx", "powerpoint", "presentation", "slide", "deck"]): return "pptx"
    if any(w in text for w in ["csv", "comma separated"]): return "csv"
    if any(w in text for w in ["json", "config", "api response"]): return "json"
    if any(w in text for w in ["yaml", "yml", "kubernetes", "docker-compose", "configuration"]): return "yaml"
    if any(w in text for w in ["python script", "py file", ".py", "python code"]): return "py"
    if any(w in text for w in ["javascript", ".js file", "js script"]): return "js"
    if any(w in text for w in ["typescript", ".ts file"]): return "ts"
    if any(w in text for w in ["html", "webpage", "web page"]): return "html"
    if any(w in text for w in ["markdown", "readme", ".md"]): return "md"
    if any(w in text for w in ["sql", "query", "database script"]): return "sql"
    if any(w in text for w in ["shell", "bash", "script", ".sh"]): return "sh"
    return "txt"


def generate_file(file_type: str, title: str, content: str, structured_data: dict = None, metadata: dict = None) -> tuple:
    """
    Master file generator.
    Returns: (storage_path, filename, mime_type)
    """
    ext = file_type.lower().lstrip(".")
    mime = MIME_MAP.get(ext, "application/octet-stream")
    metadata = metadata or {}

    try:
        if ext == "pdf":
            path, fname = generate_pdf(title, content, metadata)
        elif ext == "docx":
            path, fname = generate_docx(title, content, metadata)
        elif ext == "xlsx":
            rows = structured_data.get("rows", []) if structured_data else []
            headers = structured_data.get("headers", None) if structured_data else None
            path, fname = generate_xlsx(title, rows, headers, metadata)
        elif ext == "csv":
            rows = structured_data.get("rows", []) if structured_data else []
            headers = structured_data.get("headers", None) if structured_data else None
            path, fname = generate_csv(title, rows, headers)
        elif ext == "pptx":
            slides = structured_data.get("slides", []) if structured_data else [{"title": title, "content": content}]
            path, fname = generate_pptx(title, slides)
        elif ext == "json":
            data = structured_data or {"title": title, "content": content, "generated_at": datetime.utcnow().isoformat()}
            path, fname = generate_json_file(title, data)
        else:
            # All text-based: txt, md, py, js, ts, html, css, sql, sh, yaml, yml
            path, fname = generate_text_file(title, content, ext)

        logger.info(f"[FileGen] Generated {ext}: {fname}")
        return path, fname, mime
    except Exception as e:
        logger.error(f"[FileGen] Failed to generate {ext}: {e}")
        raise
