"""
Twin-to-Twin Direct Chat Models
================================
Separate from the A2A/Agent-Network workflow system.
Enables real-time human chat where each side is assisted by their AI Twin.
"""

from sqlalchemy import (
    Column, String, Boolean, DateTime, Text, ForeignKey,
    Integer, Index, Enum as SAEnum
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from db.database import Base
from datetime import datetime, timezone
import uuid
import enum


class ChatSessionStatus(str, enum.Enum):
    active   = "active"
    archived = "archived"
    declined = "declined"


class MessageSender(str, enum.Enum):
    human = "human"        # User typed and sent manually
    twin  = "twin"         # AI-generated and auto-sent
    system = "system"      # System notification


class MessageStatus(str, enum.Enum):
    pending   = "pending"   # AI suggestion waiting for human approval
    approved  = "approved"  # Human approved → delivered to other side
    sent      = "sent"      # Human typed message, delivered immediately
    rejected  = "rejected"  # Human rejected AI suggestion


class DirectChatSession(Base):
    """
    A bilateral chat session between two users (mediated by their Twins).
    Initiated by one user (initiator) and accepted by the other (partner).
    """
    __tablename__ = "direct_chat_sessions"

    id              = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    initiator_id    = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    partner_id      = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    title           = Column(String, nullable=True)          # Optional session title / topic
    status          = Column(String, default="active")       # active | archived | declined
    twin_mode       = Column(Boolean, default=True)          # whether AI assistance is on
    created_at      = Column(DateTime, default=datetime.utcnow)
    updated_at      = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    last_message_at = Column(DateTime, nullable=True)

    initiator = relationship("User", foreign_keys=[initiator_id])
    partner   = relationship("User", foreign_keys=[partner_id])
    messages  = relationship("DirectChatMessage", back_populates="session",
                             order_by="DirectChatMessage.created_at",
                             cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_dcs_pair", "initiator_id", "partner_id"),
    )


class DirectChatMessage(Base):
    """
    A single message in a DirectChatSession.
    Can be human-authored (sent) or AI-suggested (pending approval).
    """
    __tablename__ = "direct_chat_messages"

    id          = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id  = Column(String, ForeignKey("direct_chat_sessions.id", ondelete="CASCADE"),
                         nullable=False, index=True)
    sender_id   = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    # human | twin | system
    sender_type = Column(String, nullable=False, default="human")
    # pending | approved | sent | rejected
    status      = Column(String, nullable=False, default="sent")
    content     = Column(Text, nullable=False)
    # Stored JSON: suggested replies generated by Twin
    suggestions_json = Column(Text, nullable=True)
    # Memory context excerpts used to generate this message
    memory_context   = Column(Text, nullable=True)
    # Rich metadata: enrichment info, tool calls, etc.
    metadata_json    = Column(Text, nullable=True)
    created_at  = Column(DateTime, default=datetime.utcnow)
    updated_at  = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    session = relationship("DirectChatSession", back_populates="messages")
    sender  = relationship("User", foreign_keys=[sender_id])

    __table_args__ = (
        Index("ix_dcm_session_created", "session_id", "created_at"),
    )
